name: Auto merge Codex PRs

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: github.actor == 'codex[bot]' || 
contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });

