name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Vercel Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_gkMNqncMA8sYts6NH7FaZoBOCbIV/ezb6RpvjxY" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'
